### ISSUE TITLE
Union does not work (in my setup)

### ISSUE THREAD

**Issue by CarlosGS** [Obijuan/friki#1]
Hola Juan, qué chulada poder probar esto de los scripts en FreeCAD, muchas gracias!!

Quería comentarte un pequeño bug, el comando union() no me funciona :-S
Debe ser mi versión de alguno de los programas, tienes debajo la información por si quieres comparar.

Un saludo y que la fuerza te acompañe!!! :-)

![screenshot from 2015-03-21 23 16 17](https://cloud.githubusercontent.com/assets/1636266/6767295/97239bd2-d020-11e4-93b3-ac3bffaffbcd.png)

OS: "Fedora release 21 (Twenty One)"
Word size: 64-bit
Version: 0.14.$WCREV$
Python version: 2.7.8
Qt version: 4.8.6
Coin version: 2.5.0
SoQt version: 1.5.0
OCC version: 6.7.1

**Comment by Obijuan** [comment]
Comprueba que tienes activadas estas opciones en las preferencias:

![preferences-freecad-parts](https://cloud.githubusercontent.com/assets/1286062/6768420/a19b1104-d06a-11e4-8fff-765a33f21202.png)

y prueba otra vez (tiene que re-arrancar freecad). Es para descartar cosas y saber cuál es el problema.

**Comment by CarlosGS** [comment]
Perfecto, ya funciona, muchas gracias :-D

**Comment by Obijuan** [comment]
Genial! :-)
